# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish LinkHub.Core

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_DIR: ${{ github.workspace }}/Core
  NUGET_DIR: ${{ env.PROJECT_DIR }}/Nuget

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build
      run: dotnet pack --configuration Release --output ${{ env.NUGET_DIR }}

    # Publish package as an artifact, so we can use it in other jobs
    - uses: actions/upload-artifact@v4
      with:
        name: nuget
        if-no-files-found: error
        retention-days: 1 # Increase this later if needed
        path: ${{ env.NUGET_DIR }}/*.nupkg

  publish:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Download artifact created in previous job
    - uses: actions/download-artifact@v4
      with:
        name: nuget
        path: ${{ env.NUGET_DIR }}

    - name: Publish Nuget package
      run: dotnet nuget push ${{ env.NUGET_DIR }}/$(ls ${{ env.NUGET_DIR }}) --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
        
      
  
